# GCS = {
#     "ɴꜱʟᴡ": "NEVER SURRENDER LONE WOLF",
#     "✘ ᴇʟꜱᴛᴏɴ": "FAMILY ELSTON",
#     "𝐈⃯⃖𝐏⃯⃖": "IRREPLACEABLE MUTUALAN",
#     "𝔡'𝔩𝔬𝔤𝔦𝔠": "DIALOGIC",
#     "ɴɪɢʜᴛᴍᴀʀᴇ⍪": "NIGHTMARE",
#     "°ȿenȿιαɳ": "SENSIAN TEAM",
#     "·❦‌‌͜͡ʟᴛᴄ ⬪": "LIL' TWILIGHT",
#     "𝙶𝚁𝙴𝙰𝚃": "FAMILY GREAT",
#     "ˣ ᶜˡˡ": "MUTUALAN COLONIAL",
#     "𝔵 ʙᴀsᴇᴄᴀᴍᴘ": "BASECAMP VIRTUAL",
#     "✘ 𝙻𝙺": "LION KING MUTUALAN",
#     "ʂᴏꜰλᴍʂ •": "SOFAMS"
# }

# Data = """
# 1. 𝐍𝐠𝐨𝐞𝐤4𝐘𝐤𝐙 [ @EverythingNgoek ]
# 2. Aku vian 𝔵 ʙᴀsᴇᴄᴀᴍᴘ [ @Viansyah22 ]
# 3. Langit Ngit [ @langit_ngiit ]
# 4. 𝐈⃯⃖𝐏⃯⃖ ʀᴏʀʀ 𝙽𝚃🦖✘ 𝙻𝙺 [ @Kealmm ]
# 5. Zionn [ @Zionnnnja ]
# 6. yorr [ @yorricip ]
# 7. ˹ᴅɪꜰλᴍꜱ [ @RainChan76 ]
# 8. ˹ᴅɪꜰλᴍꜱ 𝓜𝓮𝓵𝓵 ; [ @Mellgbt ]
# 9. ʀᴀɪɴ ✘ ᴇʟꜱᴛᴏɴ [ @fathimaluciana ]
# 10. ❦‌‌͡ʟᴛᴄ⬪ᴅᴀꜰꜰᴀ [ @nexttstudy ]
# 11. ɴᴀᴋᴀʟᴀ 𝔡'𝔩𝔬𝔤𝔦𝔠 [ @yangbacamonyed ]
# 12. ˹ᴅɪꜰλᴍꜱ ғʟᴏ🦁 [ @flooxyyy ]
# 13. ˹ᴅɪꜰλᴍꜱ 𝕆𝕝𝕚𝕧𝕚𝕒 [ @hati2adhatiyggpnyahati ]
# 14. ˹ᴅɪꜰλᴍꜱ ᴏʟʟɪɴ [ @miiolline ]
# 15. ˹ᴅɪꜰλᴍꜱ•ᴄᴀʀʀɪᴏɴ [ @Xxx_breface_com ]
# 16. ʂᴏꜰλᴍʂ • sʏɪɴᴀɴ [ @Urlyvyiii ]
# 17. ˹ᴅɪꜰλᴍꜱ bening° [ @cwehujan ]
# 18. ˹ᴅɪꜰλᴍꜱ [ @Gabolehbilangjomblo ]
# 19. 𓇚 su͛ᴘᴇя ᴀɴɢᴇʟ ꭙ͢ ᴏᴄᴀꜱʟᴏᴛ [ @pepeklahkau ]
# 20. 𝑫𝑨𝑳𝑻𝑶𝑵 ˣ ᶜˡˡ [ @Art_Jordan ]
# 21. ˹ᴅɪꜰλᴍꜱ dhaf [ @dhafloh ]
# 22. pocong cantik 𝔡'𝔩𝔬𝔤𝔦𝔠 [ pocong cantik 𝔡'𝔩𝔬𝔤𝔦𝔠 ]
# 23. 𝑱𝑬 𝔡'𝔩𝔬𝔤𝔦𝔠 [ @pepekluuanjj ]
# 24. ᴊᴇɴɴɪᴇ.𝔡'𝔩𝔬𝔤𝔦𝔠 [ @yesbaby6929 ]
# 25. Mess 𝔵 ʙᴀsᴇᴄᴀᴍᴘ [ @Memesjelek22 ]
# 26. ·❦‌‌͜͡ʟᴛᴄ⬪ɴᴀʀᴅᴏ‽ ♱‌ [ ·❦‌‌͜͡ʟᴛᴄ⬪ɴᴀʀᴅᴏ‽ ♱‌ ]
# 27. ʂᴏꜰλᴍʂ • ᴍɪɴᴇ [ @Nanaliket ]
# 28. ˹𝚃𝚒𝚏𝚊𝚊˼ 𝙶𝚁𝙴𝙰𝚃 [ @tfhswty ]
# 29. ·❦‌‌͜͡ʟᴛᴄ⬪ʟᴇᴏɴ‽ ♱ [ @cleonzo ]
# 30. ive 𝔵 ʙᴀsᴇᴄᴀᴍᴘ [ @Ive_222 ]
# 31. ·❦‌‌͜͡ʟᴛᴄ⬪ᴊᴀᴇᴍᴀ ꭙ‌ᵈⁱᶠᵃᵐˢ🔥 [ @Dprian31 ]
# 32. ·❦‌‌͜͡ʟᴛᴄ⬪ᴧʏᴧᴧꭙ‌ᵈⁱᶠᵃᵐˢ🔥 [ @aykmpngg ]
# 33. 𝐁𝐈𝐑𝐔 ˣ ᶜˡˡ [ @iniibiruuuu ]
# 34. aca [ @nooneelsemore ]
# 35. ᴀʟʟᴇxᴀ [ @Allexa_dirgantara ]
# 36. ·❦‌‌͜͡ʟᴛᴄ⬪ᴊɪᴀɴ_ᴢɪᴇ [ @Ji_coffee ]
# 37. ·❦‌‌͜͡ʟᴛᴄ⬪ɪᴀɴɴ [ @hatethathuman ]
# 38. ·❦‌‌͜͡ʟᴛᴄ⬪ᴇʟ‽ ♱ [ ·❦‌‌͜͡ʟᴛᴄ⬪ᴇʟ‽ ♱ ]
# 39. ᴇʟᴠᴀɴᴏ ɴꜱʟᴡ [ @arsenihbos ]
# 40. ·❦‌‌͜͡ʟᴛᴄ ⬪ ɢᴇᴀᴇʟᴍᴇɪʀᴀ🌻ꭙ‌ᵈⁱᶠᵃᵐˢ🔥 [ @geaelmra ]
# 41. sʜᴀǫɪʟʟᴀ NT ✘ 𝙻𝙺 [ @Shaqiillaaaa ]
# 42. ˹Oᴘᴇᴛ˼ 𝙶𝚁𝙴𝙰𝚃 [ @Apinnkaa ]
# 43. ˹𝙿𝚊𝚗𝚐𝚎𝚛𝚊𝚗˼ 𝙶𝚁𝙴𝙰𝚃 [ ˹𝙿𝚊𝚗𝚐𝚎𝚛𝚊𝚗˼ 𝙶𝚁𝙴𝙰𝚃 ]
# 44. ·❦‌‌͜͡ʟᴛᴄ⬪ᴇɴᴢᴏ‽ [ ·❦‌‌͜͡ʟᴛᴄ⬪ᴇɴᴢᴏ‽ ]
# 45. 𝔞𝔫𝔤𝔢𝔩𝔩𝔩𝔦𝔠𝔭𝔢𝔞𝔯𝔩 ɴɪɢʜᴛᴍᴀʀᴇ⍪🦋 [ @angeliiiidp ]
# 46. pocong cantik 𝔡'𝔩𝔬𝔤𝔦𝔠 [ pocong cantik 𝔡'𝔩𝔬𝔤𝔦𝔠 ]
# 47. ·❦‌‌͜͡ʟᴛᴄ ⬪ ʀᴀʟᴘʜ? [ @ralphelp ]
# 48. ·❦‌‌͜͡ʟᴛᴄ⬪ʟᴇᴏɴ‽ ♱ [ @cleonzo ]
# 49. ᴊᴇɴɴɪᴇ.𝔡'𝔩𝔬𝔤𝔦𝔠 [ @yesbaby6929 ]
# 50. ㅤrαshα ɴɪɢʜᴛᴍᴀʀᴇ⍪ [ @loserrbruh ]
# 51. adv [ adv ]
# 52. ·❦‌‌͜͡ʟᴛᴄ⬪ɴᴀʀᴅᴏ‽ ♱‌ [ ·❦‌‌͜͡ʟᴛᴄ⬪ɴᴀʀᴅᴏ‽ ♱‌ ]
# 53. ·❦‌‌͜͡ʟᴛᴄ⬪ᴧʏᴧᴧꭙ‌ᵈⁱᶠᵃᵐˢ🔥 [ @aykmpngg ]
# 54. 𝚊𝚗𝚘𝚗𝚢𝚖𝚘𝚞𝚜°Ɇᵐᵖⁱʳᵉ [ @apcbaaao ]
# 55. aca [ @nooneelsemore ]
# 56. B͜͡h͜͡a͜͡d͜͡o͜͡t͜͡ ✘ ∂єνιℓ'ѕ [ @Putra_pr ]
# 57. rіs ˣ ᶜˡˡ ˏˋ°•*⁀➷ 🌷 [ @ririsaaa ]
# 58. ·❦‌‌͜͡ʟᴛᴄ⬪ᴇʟ‽ ♱ [ ·❦‌‌͜͡ʟᴛᴄ⬪ᴇʟ‽ ♱ ]
# 59. ㊰ Karl 🐍 [ @fluffshi_0 ]
# 60. ꜱɪʀᴇɴ ɴꜱʟᴡ [ @Lafijapi ]
# 61. ˹Oᴘᴇᴛ˼ 𝙶𝚁𝙴𝙰𝚃 [ @Apinnkaa ]
# 62. ˹𝙿𝙰𝙺 𝙿𝚁𝙴𝚂𝙸𝙳𝙴𝙽 [ @Am_Petirrrr ]
# 63. Barr ✘ 𝙻𝙺 [ @flowerauliya ]
# 64. ᴀʟʟᴇxᴀ [ @Allexa_dirgantara ]
# 65. ·❦‌‌͜͡ʟᴛᴄ ⬪ ᴄʜᴀʟᴀɴᴅʀᴀ [ ·❦‌‌͜͡ʟᴛᴄ ⬪ ᴄʜᴀʟᴀɴᴅʀᴀ ]
# 66. ᴄʜɪᴄɪ ɴꜱʟᴡ [ @caramelsusuuu ]
# 67. ·❦‌‌͜͡ʟᴛᴄ⬪ɴᴏʟᴀɴ [ @Whang_Ling ]
# 68. ʙᴀʙʏ [ ʙᴀʙʏ ]
# 69. ⁫ㅤˣ ᶜˡˡ [ ⁫ㅤˣ ᶜˡˡ ]
# 70. Vwxyz01 [ @mvwxyy ]
# 71. 𝕐𝑢𝗺𝚗ẳ s ɴꜱʟᴡ [ @Yungna ]
# 72. ˹𝙿𝚊𝚗𝚐𝚎𝚛𝚊𝚗˼ 𝙶𝚁𝙴𝙰𝚃 [ ˹𝙿𝚊𝚗𝚐𝚎𝚛𝚊𝚗˼ 𝙶𝚁𝙴𝙰𝚃 ]
# 73. ᴄɪʟᴏᴠ ✘ ᴇʟsᴛᴏɴ [ @nov444uuu ]
# 74. ᴍᴇʟᴏᴅʏ 𝔡'𝔩𝔬𝔤𝔦𝔠 [ @airellntg ]
# 75. ˹ᴅɪꜰλᴍꜱ baim [ @Isyam860 ]
# 76. clearlas [ clearlas ]
# 77. 𝗲𝗳𝗹𝗼𝘄 [ @imeflowbro ]
# 78. f a n n y• [ @fucknie ]
# 79. ˹ᴅɪᴍᴀs˼ 𝙶𝚁𝙴𝙰𝚃 [ @Dnakwisjdsowdk ]
# 80. ㊊ Falenn [ @falen_usn ]
# 81. defnotangel 𝔵 ʙᴀsᴇᴄᴀᴍᴘ [ defnotangel 𝔵 ʙᴀsᴇᴄᴀᴍᴘ ]
# 82. sʜᴀǫɪʟʟᴀ NT ✘ 𝙻𝙺 [ @Shaqiillaaaa ]
# 83. 𝒴𝒶𝒸𝒶𝒶𝒶𝒶 [ @Yacaaaaaaaaa ]
# 84. ˹𝚃𝚒𝚏𝚊𝚊˼ 𝙶𝚁𝙴𝙰𝚃 [ @tfhswty ]
# 85. ʟᴇᴇ ᴍᴇʏ‽ [ ʟᴇᴇ ᴍᴇʏ‽ ]
# 86. ᴅᴇɴᴀᴅᴀ ʟᴀᴢɪᴍᴀ [ ᴅᴇɴᴀᴅᴀ ʟᴀᴢɪᴍᴀ ]
# 87. ˹𝙽𝖔ÿ˼ 𝙶𝚁𝙴𝙰𝚃 [ @cewenyadan ]
# 88. ᴅiƚ ✘ ᴇʟꜱᴛᴏɴ [ @Anksetang ]
# 89. ᴊᴀʏ ✘ ᴇʟꜱᴛᴏɴ [ @Jayinheree ]
# 90. anxel 𝙶𝚁𝙴𝙰𝚃 [ anxel 𝙶𝚁𝙴𝙰𝚃 ]
# 91. ᴀᴄᴀᴀ ɴꜱʟᴡ [ @Matchalattecupp ]
# 92. ʙᴏᴄɪʟ ✘ ᴇʟꜱᴛᴏɴ [ @bocilzt ]
# 93. ɴᴏɴᴀ ɴɪɢʜᴛᴍᴀʀᴇ⍪ [ ɴᴏɴᴀ ɴɪɢʜᴛᴍᴀʀᴇ⍪ ]
# 94. ㅤᴊᴏᴘᴇʟ ɴꜱʟᴡ🫧 [ @jopelelo ]
# 95. Caca ˣ ᶜˡˡ [ Caca ˣ ᶜˡˡ ]
# 96. sᴀᴀ ✘ ᴇʟsᴛᴏɴ [ @Ansadisini ]
# 97. ʙᴀᴇ [ @nandoinhere ]
# 98. ·❦‌‌͜͡ʟᴛᴄ⬪ᴊᴀᴇᴍᴀ ꭙ‌ᵈⁱᶠᵃᵐˢ🔥 [ @Dprian31 ]
# 99. 𝕘𝕖𝕠𝕣𝕘𝕖 𝔡'𝔩𝔬𝔤𝔦𝔠 [ @kluthukbanana ]
# 100. .𝐀𝐃𝐈 ˣ ᶜˡˡ [ @cieeberharap ]
# 101. Lullu 𝔵 ʙᴀsᴇᴄᴀᴍᴘ [ @luluazaaa ]
# 102. ·❦‌‌͜͡ʟᴛᴄ⬪ꜱʜᴇᴀᴀ ꭙ‌ᵈⁱᶠᵃᵐˢ🔥 [ @kelumenjadipilu ]
# 103. ·❦‌‌͜͡ʟᴛᴄ ⬪ [ ·❦‌‌͜͡ʟᴛᴄ ⬪ ]
# 104. ♕︎ Daeng 𝔵 ʙᴀsᴇᴄᴀᴍᴘ🏴‍☠️ [ @Daeng_04 ]
# 105. ʙɪᴅᴀᴅᴀʀɪ 𝔡'𝔩𝔬𝔤𝔦𝔠 [ ʙɪᴅᴀᴅᴀʀɪ 𝔡'𝔩𝔬𝔤𝔦𝔠 ]
# 106. ʀᴇʏɴᴀ 𝔡'𝔩𝔬𝔤𝔦𝔠 [ @mommyreyna ]
# 107. ❦‌‌͜͡ʟᴛᴄ ⬪ ᴀɴɪᴛᴀ ꭙ‌ᵈⁱᶠᵃᵐˢ🔥 [ @Gemeskkitu ]
# 108. ʜᴀɴʏ ✘ ᴇʟꜱᴛᴏɴ [ @hanywee ]
# 109. Mas 𝙘𝙤𝙧𝙚 𝙶𝚁𝙴𝙰𝚃 [ @Corestaylearning ]
# 110. Anna [ @NABILAuhahha ]
# 111. fltrshy 𝔡'𝔩𝔬𝔤𝔦𝔠 [ fltrshy 𝔡'𝔩𝔬𝔤𝔦𝔠 ]
# 112. ᴀᴜʀᴀ 𝔵 ʙᴀsᴇᴄᴀᴍᴘ [ @montyok ]
# 113. ⁿᵃʸ ˣ ᶜˡˡ [ ⁿᵃʸ ˣ ᶜˡˡ ]
# 114. ʙɪᴇ 𝔡'𝔩𝔬𝔤𝔦𝔠 [ ʙɪᴇ 𝔡'𝔩𝔬𝔤𝔦𝔠 ]
# 115. ㅤˣ ᶜˡˡ [ ㅤˣ ᶜˡˡ ]
# 116. ㊊ [ @hatoriaja ]
# 117. ive 𝔵 ʙᴀsᴇᴄᴀᴍᴘ [ @Ive_222 ]
# 118. ˹𝚃𝚒𝚔𝚊˼𝙶𝚁𝙴𝙰𝚃 [ @Tiikkkaaa ]
# 119. ·❦‌‌͜͡ʟᴛᴄ ⬪ Tʏʀᴀɴᴛ [ @Call_MeRann ]
# 120. ·❦‌‌͜͡ʟᴛᴄ ⬪ ᴀᴍᴀɴᴅᴀ 𝄢 [ @Amandaawell ]
# 121. 𝐁𝐈𝐑𝐔 ˣ ᶜˡˡ [ @iniibiruuuu ]
# 122. ᴇʟᴠᴀɴᴏ ɴꜱʟᴡ [ @arsenihbos ]
# 123. ʂᴏꜰλᴍʂ • [ @gosahtagbabik ]
# 124. Mess 𝔵 ʙᴀsᴇᴄᴀᴍᴘ [ @Memesjelek22 ]
# 125. NARUTO ˣ ᶜˡˡ [ @narutomaah ]
# 126. 𝙚𝙠𝙝𝙤 𝔵 ʙᴀsᴇᴄᴀᴍᴘ 🔥🔥 [ @putramutu ]
# 127. ʙᴏᴏ [ @baemusic_assistant ]
# 128. nan [ @exebae ]
# 129. ˹𝙽𝖔ÿ cewe dan˼ 𝙶𝚁𝙴𝙰𝚃 [ @cupapymunyenyow ]
# 130. ikkeee ɴɪɢʜᴛᴍᴀʀᴇ⍪ [ @ikkeehhhh ]
# 131. ᴊʜᴏɴ ɴꜱʟᴡ [ @Haalloo911 ]
# 132. ᴍᴀᴠᴇꜱʜ ✘ ᴇʟꜱᴛᴏɴ [ @mav3sh ]
# 133. ⌖ ᴀɴɪᴍᴇ ɴɪɢʜᴛᴍᴀʀᴇ⍪ [ @kwiyowo ]
# 134. ˹𝙽𝖔ÿ baik˼ 𝙶𝚁𝙴𝙰𝚃 [ ˹𝙽𝖔ÿ baik˼ 𝙶𝚁𝙴𝙰𝚃 ]
# 135. ˹𝙽𝖔ÿ kalem˼ 𝙶𝚁𝙴𝙰𝚃 [ ˹𝙽𝖔ÿ kalem˼ 𝙶𝚁𝙴𝙰𝚃 ]
# 136. ꭙ‌_Kɪɴɢ"𝕊 ɴɪɢʜᴛᴍᴀʀᴇ⍪ [ @otoLer ]
# 137. ʂᴏꜰλᴍʂ • ᴍɪɴᴇ [ @Nanaliket ]
# 138. ɴᴏᴠᴀ ✘ ᴇʟsᴛᴏɴ [ @luvviyuuuu ]
# 139. ᴀʟᴇx ✘ ᴇʟꜱᴛᴏɴ [ @Axeleldric ]
# 140. ㅤㅤʙᴇʏꜱʜᴀ ɴɪɢʜᴛᴍᴀʀᴇ⍪ [ @markleevibez ]
# 141. ɴᴀʏʀᴀ 𝔵 ʙᴀsᴇᴄᴀᴍᴘ [ @lunoxyra ]
# 142. ·❦‌‌͜͡ʟᴛᴄ⬪ᴊɪᴀɴ_ᴢɪᴇ [ @Ji_coffee ]
# 143. gr 𝔡'𝔩𝔬𝔤𝔦𝔠 [ gr 𝔡'𝔩𝔬𝔤𝔦𝔠 ]
# 144. 𝐬𝐡𝐚𝐛𝐞𝐥𝐥𝐞 ɴɪɢʜᴛᴍᴀʀᴇ⍪ [ 𝐬𝐡𝐚𝐛𝐞𝐥𝐥𝐞 ɴɪɢʜᴛᴍᴀʀᴇ⍪ ]
# 145. ʙʀɪʟɪᴀɴᴀ 𝔡'𝔩𝔬𝔤𝔦𝔠 [ @brsranran ]
# 146. 𝑧𝑆𝑡𝑎𝑟7 ɴɪɢʜᴛᴍᴀʀᴇ⍪ [ @inistars7 ]
# 147. ·❦‌‌͜͡ʟᴛᴄ ⬪ ᴄɪɪɪꭙ‌ᵈⁱᶠᵃᵐˢ🔥 [ @ciciajaaaaaaa ]
# 148. ·❦‌‌͜͡ʟᴛᴄ⬪ꜱʜɪɪꭙ‌ᵈⁱᶠᵃᵐˢ🔥 [ ·❦‌‌͜͡ʟᴛᴄ⬪ꜱʜɪɪꭙ‌ᵈⁱᶠᵃᵐˢ🔥 ]
# 149. ·❦‌‌͜͡ʟᴛᴄ⬪ɪᴀɴɴ [ @hatethathuman ]
# 150. ㅤβօçìӀ ɴɪɢʜᴛᴍᴀʀᴇ⍪ [ @sainganbapakkau ]
# 151. ·❦‌‌͜͡ʟᴛᴄ⬪ ɴᴀᴀ​ [ @Callmenaaaaaaaaaa ]
# 152. ᵏᵉʸʸ 𝔵 ʙᴀsᴇᴄᴀᴍᴘ [ @imkeyyyyaa ]
# 153. isaaa 𝔡'𝔩𝔬𝔤𝔦𝔠 [ @shinesaain ]
# 154. 𝑱𝑬 𝔡'𝔩𝔬𝔤𝔦𝔠 [ @pepekluuanjj ]
# 155. nakir ɴɪɢʜᴛᴍᴀʀᴇ⍪ [ @morningstarmine ]
# 156. ·❦‌‌͜͡ʟᴛᴄ⬪sagara ꭙ‌ᵈⁱᶠᵃᵐˢ🔥 [ @Elah_ribet ]
# 157. ɪᴄɪʟʟᴢ 𝔡'𝔩𝔬𝔤𝔦𝔠 [ @icill_ucull ]
# 158. ·❦‌‌͜͡ʟᴛᴄ ⬪ ɢᴇᴀᴇʟᴍᴇɪʀᴀ🌻ꭙ‌ᵈⁱᶠᵃᵐˢ🔥 [ @geaelmra ] """

# temp_data = []

# for kata in Data.split():
#     print(kata)
#     # kata = kata.split('. ')[1].split(' [')[0]
    
#     # temp_data.append(kata)
    
    